# Generated by Django 5.1.15 on 2026-08-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dnsrecord',
            new_name='dns_dnsreco_zone_id_5f13bd_idx',
            old_name='dns_dnsreco_zone_id_0a1b2c_idx',
        ),
    ]
