# Generated by Django 5.1.15 on 2026-08-03 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('image', models.CharField(max_length=255)),
                ('tag', models.CharField(default='latest', max_length=64)),
                ('container_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('created', 'Créé'), ('running', 'En cours'), ('stopped', 'Arrêté'), ('error', 'Erreur'), ('removed', 'Supprimé')], default='created', max_length=16)),
                ('ports', models.JSONField(blank=True, default=dict, help_text='Mapping ports host→container, ex: {"8080": "80"}.')),
                ('env_vars', models.JSONField(blank=True, default=dict)),
                ('volumes', models.JSONField(blank=True, default=list, help_text='Volumes relatifs au home, ex: ["data:/app/data"].')),
                ('command', models.CharField(blank=True, default='', max_length=512)),
                ('restart_policy', models.CharField(choices=[('no', 'No'), ('always', 'Always'), ('unless-stopped', 'Unless stopped'), ('on-failure', 'On failure')], default='unless-stopped', max_length=32)),
                ('memory_mb', models.PositiveIntegerField(default=512)),
                ('cpus', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('last_error', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docker_containers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DockerContainerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('create', 'Create'), ('start', 'Start'), ('stop', 'Stop'), ('restart', 'Restart'), ('remove', 'Remove'), ('logs', 'Logs')], max_length=16)),
                ('success', models.BooleanField(default=True)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='docker_mgmt.dockercontainer')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='dockercontainer',
            index=models.Index(fields=['owner', 'status'], name='docker_mgmt_owner_i_f74c5b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dockercontainer',
            unique_together={('owner', 'name')},
        ),
    ]
