# Generated by Django 5.1.15 on 2026-09-30 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docker_mgmt', '0002_dockerbuildjob_dockercomposeproject'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dockerbuildjob',
            new_name='docker_mgmt_owner_i_4d0230_idx',
            old_name='docker_mgm_owner_i_build_idx',
        ),
        migrations.RenameIndex(
            model_name='dockercomposeproject',
            new_name='docker_mgmt_owner_i_a0d725_idx',
            old_name='docker_mgm_owner_i_comp_idx',
        ),
    ]
