# Generated by Django 5.1.15 on 2026-08-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='wordpresssite',
            new_name='wordpress_w_owner_i_4612c8_idx',
            old_name='wordpress_w_owner_i_7c2a1b_idx',
        ),
    ]
