# Generated by Django 5.1.15 on 2026-08-03 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('node_version', models.CharField(default='20', max_length=16)),
                ('framework', models.CharField(choices=[('generic', 'Générique'), ('express', 'Express'), ('nest', 'NestJS'), ('next', 'Next.js')], default='generic', max_length=16)),
                ('relative_root', models.CharField(default='', help_text='Chemin relatif au home (ex: nodeapps/myapp).', max_length=255)),
                ('start_script', models.CharField(default='start', help_text='Script npm (package.json scripts).', max_length=64)),
                ('entrypoint', models.CharField(default='server.js', help_text="Fichier d'entrée si pas de script npm.", max_length=255)),
                ('port', models.PositiveIntegerField(default=0)),
                ('env_vars', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('stopped', 'Arrêtée'), ('running', 'En cours'), ('error', 'Erreur'), ('provisioning', 'Provisionnement')], default='stopped', max_length=16)),
                ('pid', models.PositiveIntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('domain_name', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_apps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['owner', 'status'], name='node_apps_n_owner_i_6eca06_idx')],
                'unique_together': {('owner', 'name')},
            },
        ),
    ]
