# Generated by Django 5.x for AI BYOK

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAiProviderSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("server", "Serveur (défaut panel)"),
                            ("ollama", "Ollama (URL perso)"),
                            ("openai_compat", "API OpenAI-compatible"),
                        ],
                        db_index=True,
                        default="server",
                        max_length=32,
                    ),
                ),
                ("base_url", models.CharField(blank=True, default="", max_length=512)),
                ("api_key_encrypted", models.TextField(blank=True, default="")),
                ("model_name", models.CharField(blank=True, default="", max_length=128)),
                ("enabled", models.BooleanField(default=True)),
                ("last_test_ok", models.BooleanField(blank=True, null=True)),
                ("last_test_message", models.CharField(blank=True, default="", max_length=255)),
                ("last_tested_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_provider_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI provider settings",
                "verbose_name_plural": "AI provider settings",
            },
        ),
    ]
