# Generated by Django 5.1.15 on 2026-08-04 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('archive', 'Archive cPanel (pkgacct/cpmove)'), ('remote_whm', 'Serveur WHM distant')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=16)),
                ('username', models.CharField(db_index=True, max_length=32)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('password', models.CharField(blank=True, default='', max_length=128)),
                ('package_name', models.CharField(blank=True, default='', max_length=64)),
                ('overwrite', models.BooleanField(default=False, help_text='Si le compte existe déjà, écraser home / réimporter métadonnées.')),
                ('archive_name', models.CharField(blank=True, default='', max_length=255)),
                ('archive_path', models.CharField(blank=True, default='', max_length=1024)),
                ('remote_host', models.CharField(blank=True, default='', max_length=255)),
                ('remote_port', models.PositiveIntegerField(default=2087)),
                ('remote_user', models.CharField(blank=True, default='', max_length=64)),
                ('remote_token', models.CharField(blank=True, default='', max_length=512)),
                ('remote_username', models.CharField(blank=True, default='', help_text='Username cPanel distant à transférer.', max_length=32)),
                ('remote_insecure_ssl', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=dict, help_text='Ex: {"home": true, "databases": true, "email": true, "dns": true, "ssl": true, "ftp": true}')),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('current_step', models.CharField(blank=True, default='', max_length=255)),
                ('log', models.TextField(blank=True, default='')),
                ('result', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_jobs_created_users', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_jobs_started', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='transfer_tr_status_202eb5_idx'), models.Index(fields=['username'], name='transfer_tr_usernam_017dc9_idx')],
            },
        ),
    ]
