# Generated by Django 5.1.15 on 2026-08-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='resourcesnapshot',
            new_name='dashboard_r_collect_7c682d_idx',
            old_name='dashboard_r_collect_0a1b2c_idx',
        ),
    ]
