# Generated by Django 5.1.15 on 2026-08-03 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PythonApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('python_version', models.CharField(default='3.12', max_length=16)),
                ('mode', models.CharField(choices=[('wsgi', 'WSGI'), ('asgi', 'ASGI')], default='wsgi', max_length=8)),
                ('framework', models.CharField(choices=[('generic', 'Générique'), ('django', 'Django'), ('flask', 'Flask'), ('fastapi', 'FastAPI')], default='generic', max_length=16)),
                ('relative_root', models.CharField(default='', help_text='Chemin relatif au home (ex: apps/myapp).', max_length=255)),
                ('entrypoint', models.CharField(default='passenger_wsgi.py', help_text="Module/fichier d'entrée (passenger_wsgi.py ou app:app).", max_length=255)),
                ('port', models.PositiveIntegerField(default=0)),
                ('env_vars', models.JSONField(blank=True, default=dict)),
                ('requirements_file', models.CharField(default='requirements.txt', max_length=64)),
                ('venv_path', models.CharField(blank=True, default='', max_length=512)),
                ('status', models.CharField(choices=[('stopped', 'Arrêtée'), ('running', 'En cours'), ('error', 'Erreur'), ('provisioning', 'Provisionnement')], default='stopped', max_length=16)),
                ('pid', models.PositiveIntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('domain_name', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='python_apps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['owner', 'status'], name='python_apps_owner_i_ef5728_idx')],
                'unique_together': {('owner', 'name')},
            },
        ),
    ]
