# Generated by Django 5.1.15 on 2026-08-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythonapp',
            name='relative_root',
            field=models.CharField(default='', help_text='Application root cPanel : chemin du projet relatif au home (ex: mydjango). passenger_wsgi.py et manage.py doivent être dans ce même dossier.', max_length=255),
        ),
    ]
