# Generated by Django 5.1.15 on 2026-08-03 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhpVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(db_index=True, max_length=16, unique=True)),
                ('binary_path', models.CharField(blank=True, default='', max_length=512)),
                ('fpm_socket', models.CharField(blank=True, default='', max_length=512)),
                ('is_available', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-version',),
            },
        ),
        migrations.CreateModel(
            name='PhpSelector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_path', models.CharField(default='public_html', help_text='Chemin relatif au home (ex: public_html ou domains/exemple.com).', max_length=255)),
                ('domain_name', models.CharField(blank=True, default='', max_length=255)),
                ('handler', models.CharField(choices=[('fpm', 'PHP-FPM'), ('cgi', 'CGI'), ('lsapi', 'LSAPI')], default='fpm', max_length=16)),
                ('ini_settings', models.JSONField(blank=True, default=dict, help_text='Surcharges php.ini (memory_limit, display_errors…).')),
                ('extensions', models.JSONField(blank=True, default=list, help_text='Extensions activées (liste de noms).')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='php_selectors', to=settings.AUTH_USER_MODEL)),
                ('php_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selectors', to='php.phpversion')),
            ],
            options={
                'ordering': ('relative_path',),
                'indexes': [models.Index(fields=['owner', 'is_active'], name='php_phpsele_owner_i_1eead5_idx')],
                'unique_together': {('owner', 'relative_path')},
            },
        ),
    ]
