# Generated by Django 5.1.15 on 2026-08-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_resourc_a674ad_idx',
            old_name='core_auditl_resourc_0a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_action_29a2bf_idx',
            old_name='core_auditl_action_1d2e3f_idx',
        ),
    ]
