# Generated by Django 5.1.15 on 2026-08-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='hostingpackage',
            new_name='packages_ho_package_33a1be_idx',
            old_name='packages_ho_package_0a1b2c_idx',
        ),
    ]
