# Generated by Django 5.1.15 on 2026-08-05 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cronjob',
            new_name='cron_cronjo_owner_i_6939ae_idx',
            old_name='cron_cronjo_owner_i_7a1b2c_idx',
        ),
    ]
