# Generated by Django 5.1.15 on 2026-08-03 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLockout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SecurityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_min_length', models.PositiveSmallIntegerField(default=10)),
                ('require_uppercase', models.BooleanField(default=False)),
                ('require_digit', models.BooleanField(default=True)),
                ('require_special', models.BooleanField(default=False)),
                ('lockout_max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('lockout_window_minutes', models.PositiveSmallIntegerField(default=15)),
                ('lockout_duration_minutes', models.PositiveSmallIntegerField(default=30)),
                ('ip_mode', models.CharField(choices=[('off', 'Désactivé'), ('allowlist', 'Allowlist seule'), ('blocklist', 'Blocklist')], default='off', max_length=16)),
                ('force_2fa_admins', models.BooleanField(default=False, help_text='Exige 2FA pour administrateurs et revendeurs.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Politique de sécurité',
                'verbose_name_plural': 'Politiques de sécurité',
            },
        ),
        migrations.CreateModel(
            name='IpAccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidr', models.CharField(max_length=64)),
                ('list_type', models.CharField(choices=[('allow', 'Allow'), ('block', 'Block')], max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_access_rules_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('list_type', 'cidr'),
                'indexes': [models.Index(fields=['list_type', 'is_active'], name='security_ip_list_ty_9ecd30_idx')],
            },
        ),
    ]
