# Default catch-all for unmatched Host on OLS backend
docRoot                   /var/lib/vzone/ols/default/
vhDomain                  _
enableGzip                1

index  {
  useServer               0
  indexFiles              index.html
}

accessControl  {
  allow                   *
}

rewrite  {
  enable                  0
}
