# Generated by Django 5.1.15 on 2026-08-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ftpaccount',
            new_name='ftp_ftpacco_owner_i_007dd2_idx',
            old_name='ftp_ftpacco_owner_i_0a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='ftpaccount',
            new_name='ftp_ftpacco_is_susp_76a7ef_idx',
            old_name='ftp_ftpacco_is_susp_1d2e3f_idx',
        ),
        migrations.RenameIndex(
            model_name='ftplog',
            new_name='ftp_ftplog_usernam_74c59f_idx',
            old_name='ftp_ftplog_usernam_2a3b4c_idx',
        ),
        migrations.RenameIndex(
            model_name='ftplog',
            new_name='ftp_ftplog_event_t_c51f7e_idx',
            old_name='ftp_ftplog_event_t_3b4c5d_idx',
        ),
    ]
