# Generated by Django 5.1.15 on 2026-08-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_role_2b136f_idx',
            old_name='accounts_us_role_7a0e3a_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_parent__a6ff31_idx',
            old_name='accounts_us_parent__7f2c1a_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
    ]
