# Generated by Django 5.1.15 on 2026-08-03 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(choices=[('mysql', 'MySQL / MariaDB'), ('postgresql', 'PostgreSQL')], default='mysql', max_length=16)),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('charset', models.CharField(default='utf8mb4', max_length=32)),
                ('collation', models.CharField(default='utf8mb4_unicode_ci', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('size_mb', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_databases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DatabaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(choices=[('mysql', 'MySQL / MariaDB'), ('postgresql', 'PostgreSQL')], default='mysql', max_length=16)),
                ('username', models.CharField(db_index=True, max_length=64)),
                ('password_hash', models.CharField(max_length=256)),
                ('host', models.CharField(default='localhost', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('username',),
            },
        ),
        migrations.CreateModel(
            name='DatabasePrivilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privileges', models.CharField(choices=[('ALL', 'Tous'), ('READ', 'Lecture'), ('WRITE', 'Écriture')], default='ALL', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privileges', to='databases.database')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privileges', to='databases.databaseuser')),
            ],
            options={
                'ordering': ('database__name', 'user__username'),
            },
        ),
        migrations.AddIndex(
            model_name='database',
            index=models.Index(fields=['owner', 'engine'], name='databases_d_owner_i_8d44cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='database',
            unique_together={('engine', 'name')},
        ),
        migrations.AddIndex(
            model_name='databaseuser',
            index=models.Index(fields=['owner', 'engine'], name='databases_d_owner_i_b0e0fc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='databaseuser',
            unique_together={('engine', 'username', 'host')},
        ),
        migrations.AlterUniqueTogether(
            name='databaseprivilege',
            unique_together={('database', 'user')},
        ),
    ]
