# Generated by Django 5.1.15 on 2026-08-03 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('backup_type', models.CharField(choices=[('full', 'Complète'), ('home', 'Fichiers'), ('databases', 'Bases'), ('email', 'Email'), ('custom', 'Personnalisée')], default='full', max_length=16)),
                ('includes', models.JSONField(blank=True, default=list, help_text='Composants inclus, ex: ["home", "databases", "email"].')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('completed', 'Terminée'), ('failed', 'Échouée'), ('restoring', 'Restauration'), ('restored', 'Restaurée')], default='pending', max_length=16)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('last_error', models.TextField(blank=True, default='')),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_archives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BackupEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('create', 'Create'), ('complete', 'Complete'), ('restore', 'Restore'), ('delete', 'Delete'), ('download', 'Download'), ('schedule', 'Schedule'), ('fail', 'Fail')], max_length=16)),
                ('success', models.BooleanField(default=True)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='backups.backuparchive')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_event_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel')], default='weekly', max_length=16)),
                ('includes', models.JSONField(blank=True, default=list)),
                ('hour', models.PositiveSmallIntegerField(default=2)),
                ('weekday', models.PositiveSmallIntegerField(default=0, help_text='0=lundi … 6=dimanche (hebdomadaire).')),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backup_schedule', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('owner__username',),
            },
        ),
        migrations.AddIndex(
            model_name='backuparchive',
            index=models.Index(fields=['owner', 'status'], name='backups_bac_owner_i_689611_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='backuparchive',
            unique_together={('owner', 'name')},
        ),
    ]
