# Generated by Django 5.1.15 on 2026-08-03 10:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("domains", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_part', models.CharField(max_length=64)),
                ('password_hash', models.CharField(max_length=256)),
                ('quota_mb', models.PositiveIntegerField(default=250, validators=[django.core.validators.MinValueValidator(1)])),
                ('used_mb', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('maildir', models.CharField(blank=True, default='', max_length=512)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('local_part',),
            },
        ),
        migrations.CreateModel(
            name='Autoresponder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('subject', models.CharField(default='Absence du bureau', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('interval_hours', models.PositiveIntegerField(default=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mailbox', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autoresponder', to='email.mailbox')),
            ],
        ),
        migrations.CreateModel(
            name='MailDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('catch_all', models.EmailField(blank=True, default='', max_length=254)),
                ('max_quota_mb', models.PositiveIntegerField(default=1024)),
                ('dkim_enabled', models.BooleanField(default=False)),
                ('dkim_selector', models.CharField(default='default', max_length=63)),
                ('dkim_private_key', models.TextField(blank=True, default='')),
                ('dkim_public_key', models.TextField(blank=True, default='')),
                ('spf_record', models.CharField(blank=True, default='', max_length=512)),
                ('dmarc_policy', models.CharField(choices=[('none', 'none'), ('quarantine', 'quarantine'), ('reject', 'reject')], default='none', max_length=16)),
                ('dmarc_rua', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_domain', to='domains.domain')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_domains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='mailbox',
            name='mail_domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailboxes', to='email.maildomain'),
        ),
        migrations.CreateModel(
            name='MailFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('match_field', models.CharField(choices=[('subject', 'Sujet'), ('from', 'De'), ('to', 'À'), ('body', 'Corps')], default='subject', max_length=32)),
                ('match_op', models.CharField(choices=[('contains', 'Contient'), ('equals', 'Égal'), ('startswith', 'Commence par')], default='contains', max_length=16)),
                ('match_value', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('discard', 'Supprimer'), ('deliver', 'Délivrer dans dossier'), ('forward', 'Transférer'), ('stop', 'Arrêter')], default='deliver', max_length=16)),
                ('action_value', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='email.mailbox')),
            ],
            options={
                'ordering': ('priority', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MailForwarder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_part', models.CharField(max_length=64)),
                ('destinations', models.JSONField(default=list, help_text="Liste d'adresses de destination.")),
                ('keep_copy', models.BooleanField(default=False, help_text='Conserver une copie locale si une boîte existe.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mail_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwarders', to='email.maildomain')),
            ],
            options={
                'ordering': ('local_part',),
            },
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_part', models.CharField(max_length=64)),
                ('members', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mail_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='email.maildomain')),
            ],
        ),
        migrations.AddIndex(
            model_name='mailbox',
            index=models.Index(fields=['mail_domain', 'is_active'], name='email_mailb_mail_do_afc109_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mailbox',
            unique_together={('mail_domain', 'local_part')},
        ),
        migrations.AlterUniqueTogether(
            name='mailforwarder',
            unique_together={('mail_domain', 'local_part')},
        ),
        migrations.AlterUniqueTogether(
            name='mailinglist',
            unique_together={('mail_domain', 'local_part')},
        ),
    ]
