#!/usr/bin/env bash
# Installe OpenLiteSpeed + lsphp (moteur optionnel derrière Nginx).
# Activation : VZONE_OLS_ENABLED=1 dans /etc/vzone/vzone.env
set -euo pipefail
[[ ${EUID:-0} -eq 0 ]] || { echo "Root requis"; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
VZONE_USER="${VZONE_USER:-vzone}"
VZONE_DATA="${VZONE_DATA_ROOT:-/var/lib/vzone}"
OLS_ROOT="${VZONE_OLS_ROOT:-/usr/local/lsws}"
OLS_LISTEN="${VZONE_OLS_LISTEN:-127.0.0.1:8088}"
OLS_DIR="${VZONE_DATA}/ols"
VH_DIR="${OLS_DIR}/vhosts"
VHCONF_DIR="${OLS_DIR}/vhconf"
LOG_DIR="${OLS_DIR}/logs"

echo "[vzone] Installation OpenLiteSpeed (backend local ${OLS_LISTEN})"

mkdir -p "${VH_DIR}" "${VHCONF_DIR}" "${LOG_DIR}"
chown -R "${VZONE_USER}:${VZONE_USER}" "${OLS_DIR}"
chmod 775 "${OLS_DIR}" "${VH_DIR}" "${VHCONF_DIR}" "${LOG_DIR}"

# Dépôt LiteSpeed (Debian/Ubuntu)
if [[ ! -f /etc/apt/sources.list.d/lst_debian_repo.list ]] && [[ ! -f /etc/apt/sources.list.d/lst_ubuntu_repo.list ]]; then
  if command -v apt-get >/dev/null 2>&1; then
    curl -fsSL https://repo.litespeed.sh | bash || {
      echo "[vzone] Avertissement: dépôt LiteSpeed non ajouté — tentez manuellement: curl -fsSL https://repo.litespeed.sh | bash" >&2
    }
  fi
fi

if command -v apt-get >/dev/null 2>&1; then
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -qq || true
  apt-get install -y openlitespeed \
    lsphp81 lsphp81-common lsphp81-mysql lsphp81-curl lsphp81-opcache \
    lsphp82 lsphp82-common lsphp82-mysql lsphp82-curl lsphp82-opcache \
    lsphp83 lsphp83-common lsphp83-mysql lsphp83-curl lsphp83-opcache \
    2>/dev/null || apt-get install -y openlitespeed lsphp81 lsphp82 lsphp83 || {
      echo "[vzone] ERREUR: paquets OpenLiteSpeed / lsphp introuvables" >&2
      exit 1
    }
elif command -v dnf >/dev/null 2>&1; then
  dnf install -y openlitespeed lsphp81 lsphp82 lsphp83 || true
else
  echo "[vzone] ERREUR: gestionnaire de paquets non supporté" >&2
  exit 1
fi

# Désactiver le listener public OLS par défaut (Nginx garde 80/443)
# On injecte notre snippet V-zone.
SNIPPET_SRC="${REPO_DIR}/deploy/openlitespeed/vzone-backend.conf"
SNIPPET_DST="${OLS_ROOT}/conf/vzone-backend.conf"
HTTPD_CONF="${OLS_ROOT}/conf/httpd_config.conf"

if [[ -f "${SNIPPET_SRC}" ]]; then
  # Remplacer le placeholder d'écoute
  sed "s|__VZONE_OLS_LISTEN__|${OLS_LISTEN}|g" "${SNIPPET_SRC}" > "${SNIPPET_DST}"
  chmod 644 "${SNIPPET_DST}"
fi

if [[ -f "${HTTPD_CONF}" ]]; then
  # Commenter les listeners *:80 / *:443 OLS pour éviter le conflit avec Nginx
  if grep -qE 'address\s+\*:80' "${HTTPD_CONF}"; then
    sed -i.bak -E 's/^([[:space:]]*address[[:space:]]+)\*:80/\1'127.0.0.1:8080'/' "${HTTPD_CONF}" || true
  fi
  if grep -qE 'address\s+\*:443' "${HTTPD_CONF}"; then
    sed -i.bak -E 's/^([[:space:]]*address[[:space:]]+)\*:443/\1'127.0.0.1:8443'/' "${HTTPD_CONF}" || true
  fi
  if ! grep -q 'vzone-backend.conf' "${HTTPD_CONF}"; then
    printf '\n# V-zone OpenLiteSpeed backend (behind Nginx)\ninclude %s\n' "${SNIPPET_DST}" >> "${HTTPD_CONF}"
  fi
fi

# Fichier maps/vhosts généré par le panel
MAPS="${OLS_DIR}/vzone-vhosts.conf"
cat > "${MAPS}" <<EOF
# Generated by V-zone — OpenLiteSpeed backend
listener vzoneHttp {
  address                 ${OLS_LISTEN}
  secure                  0
  map                     DEFAULT vzoneDefault
}

virtualhost vzoneDefault {
  vhRoot                  /var/lib/vzone/ols/default
  configFile              /var/lib/vzone/ols/vhconf/vzoneDefault.conf
  allowSymbolLink         1
  enableScript            1
  restrained              1
  setUIDMode              0
}
EOF
chown "${VZONE_USER}:${VZONE_USER}" "${MAPS}"

# Docroot + vhconf par défaut
mkdir -p "${OLS_DIR}/default"
cat > "${OLS_DIR}/default/index.html" <<'HTMLEOF'
<!DOCTYPE html>
<html lang="fr"><head><meta charset="utf-8"><title>V-zone</title>
<style>body{font-family:system-ui;display:flex;min-height:100vh;align-items:center;justify-content:center;margin:0;background:#0b1220;color:#9db0c7}
.box{text-align:center;padding:2rem}h1{color:#fff;font-size:1.2rem}</style></head>
<body><div class="box"><h1>OpenLiteSpeed — backend V-zone</h1>
<p>Aucun vhost mappé pour ce Host. Créez un domaine dans le panel (moteur OpenLiteSpeed).</p>
</div></body></html>
HTMLEOF
if [[ -f "${REPO_DIR}/deploy/openlitespeed/vhconf-default.conf" ]]; then
  install -m 644 "${REPO_DIR}/deploy/openlitespeed/vhconf-default.conf" "${VHCONF_DIR}/vzoneDefault.conf"
fi
chown -R "${VZONE_USER}:${VZONE_USER}" "${OLS_DIR}/default" "${VHCONF_DIR}"

# Agent reload
install -m 755 "${REPO_DIR}/scripts/vzone-ols-reload.sh" /usr/local/sbin/vzone-ols-reload
install -m 644 "${REPO_DIR}/deploy/systemd/vzone-ols-reload.service" /etc/systemd/system/vzone-ols-reload.service
install -m 644 "${REPO_DIR}/deploy/systemd/vzone-ols-reload.path" /etc/systemd/system/vzone-ols-reload.path

systemctl daemon-reload
systemctl enable --now lshttpd 2>/dev/null || systemctl enable --now lsws 2>/dev/null || true
systemctl enable --now vzone-ols-reload.path

# Graceful restart
if [[ -x "${OLS_ROOT}/bin/lswsctrl" ]]; then
  "${OLS_ROOT}/bin/lswsctrl" restart || true
else
  systemctl restart lshttpd 2>/dev/null || systemctl restart lsws 2>/dev/null || true
fi

# Marqueur install
echo "1" > "${OLS_DIR}/.installed"
chown "${VZONE_USER}:${VZONE_USER}" "${OLS_DIR}/.installed"

# Activer dans l'env panel (auto = activé dès qu'installé)
ENV_FILE="/etc/vzone/vzone.env"
if [[ -f "${ENV_FILE}" ]]; then
  if grep -qE '^VZONE_OLS_ENABLED=' "${ENV_FILE}"; then
    sed -i 's/^VZONE_OLS_ENABLED=.*/VZONE_OLS_ENABLED=auto/' "${ENV_FILE}" || true
  else
    printf '\n# OpenLiteSpeed (auto = actif si installé)\nVZONE_OLS_ENABLED=auto\nVZONE_OLS_LISTEN=%s\n' "${OLS_LISTEN}" >> "${ENV_FILE}"
  fi
  if ! grep -qE '^VZONE_OLS_DEFAULT_ENGINE=' "${ENV_FILE}"; then
    echo "VZONE_OLS_DEFAULT_ENGINE=1" >> "${ENV_FILE}"
  fi
fi

echo "[vzone] OpenLiteSpeed prêt (listener ${OLS_LISTEN})"
echo "[vzone] Mode: VZONE_OLS_ENABLED=auto — nouveaux domaines → OLS (comme cPanel)"
echo "[vzone] Redémarrez l'API: systemctl restart vzone-api"
