# Generated by Django 5.1.15 on 2026-08-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='domain',
            new_name='domains_dom_owner_i_4f2b13_idx',
            old_name='domains_dom_owner_i_0a1b2c_idx',
        ),
    ]
