# Generated by Django 5.1.15 on 2026-08-03 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('remote_url', models.CharField(max_length=512)),
                ('branch', models.CharField(default='main', max_length=128)),
                ('relative_path', models.CharField(help_text='Chemin relatif au home (ex: repositories/app).', max_length=255)),
                ('deploy_script', models.CharField(blank=True, default='', help_text='Script post-pull relatif au dépôt (ex: deploy.sh).', max_length=255)),
                ('auto_deploy', models.BooleanField(default=True)),
                ('webhook_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('deploy_key_public', models.TextField(blank=True, default='')),
                ('deploy_key_private', models.TextField(blank=True, default='')),
                ('last_commit', models.CharField(blank=True, default='', max_length=64)),
                ('last_commit_message', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('idle', 'Inactif'), ('cloning', 'Clone'), ('deploying', 'Déploiement'), ('ready', 'Prêt'), ('error', 'Erreur')], default='idle', max_length=16)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_deploy_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_repositories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GitDeployLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('clone', 'Clone'), ('pull', 'Pull'), ('deploy', 'Deploy'), ('webhook', 'Webhook'), ('keygen', 'Clé deploy')], max_length=16)),
                ('success', models.BooleanField(default=True)),
                ('message', models.TextField(blank=True, default='')),
                ('commit_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='git_deploy.gitrepository')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='gitrepository',
            index=models.Index(fields=['owner', 'status'], name='git_deploy__owner_i_c908ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gitrepository',
            unique_together={('owner', 'name')},
        ),
        migrations.AddIndex(
            model_name='gitdeploylog',
            index=models.Index(fields=['repository', 'created_at'], name='git_deploy__reposit_d446be_idx'),
        ),
    ]
