# Generated by Django 5.1.15 on 2026-08-03 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fail2BanJail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('filter_name', models.CharField(blank=True, default='', max_length=64)),
                ('max_retry', models.PositiveIntegerField(default=5)),
                ('find_time', models.PositiveIntegerField(default=600, help_text='Secondes')),
                ('ban_time', models.PositiveIntegerField(default=3600, help_text='Secondes')),
                ('currently_banned', models.PositiveIntegerField(default=0)),
                ('total_banned', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FirewallEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('rule_create', 'Rule create'), ('rule_update', 'Rule update'), ('rule_delete', 'Rule delete'), ('rule_apply', 'Rule apply'), ('ban', 'Ban'), ('unban', 'Unban'), ('sync', 'Sync'), ('fail', 'Fail')], max_length=16)),
                ('success', models.BooleanField(default=True)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firewall_event_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Fail2BanBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('active', 'Actif'), ('unbanned', 'Débanni')], default='active', max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('banned_at', models.DateTimeField(auto_now_add=True)),
                ('unbanned_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fail2ban_bans_created', to=settings.AUTH_USER_MODEL)),
                ('jail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='firewall.fail2banjail')),
            ],
            options={
                'ordering': ('-banned_at',),
                'indexes': [models.Index(fields=['status', 'ip_address'], name='firewall_fa_status_5a20ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('action', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], default='allow', max_length=8)),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP'), ('any', 'Any')], default='tcp', max_length=8)),
                ('direction', models.CharField(choices=[('in', 'Inbound'), ('out', 'Outbound')], default='in', max_length=8)),
                ('port_start', models.PositiveIntegerField(blank=True, null=True)),
                ('port_end', models.PositiveIntegerField(blank=True, null=True)),
                ('source_cidr', models.CharField(blank=True, default='', help_text='IP ou CIDR source', max_length=64)),
                ('dest_cidr', models.CharField(blank=True, default='', help_text='IP ou CIDR destination', max_length=64)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_applied', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firewall_rules_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('priority', 'name'),
                'indexes': [models.Index(fields=['is_enabled', 'action'], name='firewall_fi_is_enab_8cea7e_idx')],
            },
        ),
    ]
